// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaKuMVqxXAKy7CxInGvKnNMHD7WZrNt2s',
    appId: '1:126628204595:web:fbf5eaa62c7ff3cb055346',
    messagingSenderId: '126628204595',
    projectId: 'guruh-5',
    authDomain: 'guruh-5.firebaseapp.com',
    storageBucket: 'guruh-5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZJJYMwVQ8VOqBVHg9GjC-zIHBke_aDoc',
    appId: '1:126628204595:android:639b9eb20519e088055346',
    messagingSenderId: '126628204595',
    projectId: 'guruh-5',
    storageBucket: 'guruh-5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE53TJk0fbM_0pDex0MP2wn4bgPHcID84',
    appId: '1:126628204595:ios:9dc96f8a2fc23d62055346',
    messagingSenderId: '126628204595',
    projectId: 'guruh-5',
    storageBucket: 'guruh-5.firebasestorage.app',
    iosBundleId: 'com.example.guruh5',
  );
}
